apiVersion: v1
kind: Service
metadata:
  name: nginx
  annotations:
    magallanes: 'true'
    magallanes/external: 'true'
    magallanes/hostname: 'example.domain.com'
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
  type: LoadBalancer
